[project]
name = "ieeLabTools"
version = "0.1.0"
description = "General symbolic + numeric uncertainty propagation, weighted linear regression"
authors = [
  { name = "Ilari Pirkkalainen", email = "iladev0@gmail.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "sympy",
  "numpy"
]

[project.urls]
Homepage = "https://github.com/ieepirzy/PhySiLight-Tools/Packages/ieeLabTools"
Documentation = "https://ieepirzy/PhySiLight-Tools/Packages/ieeLabTools/README.md"
Source = "https://github.com/ieepirzy/PhySiLight-Tools/Packages/ieeLabTools/ieeLabTools/core.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"